# Generated by Django 3.2.18 on 2023-05-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_slug'),
    ]

    operations = [
    ]
