# Generated by Django 3.2.18 on 2023-05-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_alter_comment_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prep_time',
            new_name='preping_time',
        ),
    ]
